# Generated by Django 3.1 on 2021-05-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Very Important'), ('MEDIUM', 'Important'), ('LOW', 'Not So Important')], default='LOW', max_length=6),
        ),
    ]
